# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbdash < Formula
  desc "Read-only CLI viewer for PocketBase instances"
  homepage "https://github.com/jiseop121/pbdash"
  version "0.7.3"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jiseop121/pbdash/releases/download/v0.7.3/pbdash-v0.7.3-darwin-amd64.tar.gz"
    sha256 "8a340dcec3e2541cc14924c8d7a5dc89d1041324363c998319086ef7d09551ae"

    define_method(:install) do
      bin.install "pbdash"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jiseop121/pbdash/releases/download/v0.7.3/pbdash-v0.7.3-darwin-arm64.tar.gz"
    sha256 "6a614afb16f9595f8cb98c132056e05db3260d9f9eb9c3a23d02ecb96f0f5167"

    define_method(:install) do
      bin.install "pbdash"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pbdash -c \"version\"")
  end
end
