# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pbdash < Formula
  desc "Read-only CLI viewer for PocketBase instances"
  homepage "https://github.com/jiseop121/pbdash"
  version "0.7.0"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/jiseop121/pbdash/releases/download/v0.7.0/pbdash-v0.7.0-darwin-amd64.tar.gz"
    sha256 "0aa2bf29fe1990dcef3a385375f71762ffdda047f022a8ea1f57b93a3ea92dae"

    define_method(:install) do
      bin.install "pbdash"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/jiseop121/pbdash/releases/download/v0.7.0/pbdash-v0.7.0-darwin-arm64.tar.gz"
    sha256 "eacaa429753641a15729f45e34caf75d9ab63976502228ce53efa1e00be33900"

    define_method(:install) do
      bin.install "pbdash"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pbdash -c \"version\"")
  end
end
